baseURL = "https://relaxed-saha-198f20.netlify.app/"
languageCode = "en-us"
title = "전국여대생대표자협의회 아카이브"
theme = "tailwind-aa-theme"

[build]
writeStats = true

disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "categories", "tags"]

# 메뉴관련 처리

[menu]

  [[menu.main]]
  name = "Home"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  URL = "/about"
  weight = 2

  ############# footer menu #############
  [[menu.footer]]
  name = "Marketing Layout"
  URL = "marketing"
  weight = 1
