baseURL = "https://www.jydh.or.kr"
languageCode = "ko-kr"
title = "전국여대생대표자협의회 아카이브"
description = "이 디지털아카이브는 \"전국여대생대표자협의회\" 자료를 모아 만든 기억의 창고입니다. 전국여대생대표자협의회는 1988년부터 2007년까지 전국의 대학내 여성주의 활동을 했던 여생학생 대표자 협의회 기구입니다."
theme = ["tailwind-aa-theme","hugo-search-fuse-js-aa"]
images = ['img/1-여성학회건설을 위한 토론회 자료집-표지.jpg']

[build]
writeStats = true

[taxonomies]
  tag = "tags"
  creator = "creators"


 [module]

# 메뉴관련 처리

[menu]

  [[menu.main]]
  name = "홈"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "탐색"
  URL = "/items"
  weight = 2

  [[menu.main]]
  name = "검색"
  URL = "/search"
  weight = 3

  [[menu.main]]
  name = "태그" # (주제어)
  URL = "/tags"
  weight = 4

  # [[menu.main]]
  # name = "태그(생산자)"
  # URL = "/creators"
  # weight = 5

  # [[menu.main]]
  # name = "사이트맵"
  # URL = "/sitemap.xml"
  # weight = 6          

  ############# footer menu #############
  [[menu.footer]]
  name = "Marketing Layout"
  URL = "marketing"
  weight = 1
